### ISSUE TITLE
Firedac SQLite Error

### ISSUE THREAD

**Issue by southboiafrica** [EmbarcaderoPublic/DelphiArcadeGames#1]
Trying to compile the arcade games, receive this error.

`[dcc32 Fatal Error] uHighScores.pas(28): F2613 Unit 'FireDAC.Phys.SQLiteWrapper.Stat' not found.]`

My Delphi version:
Delphi 10.3 Version 26.0.36039.7899

Error takes me uHighScores.pas on Mars Rocket example.

**Comment by FMXExpress** [comment]
Requires Delphi 10.4. You could use the Starter version of Mars Rocket or remove that unit.
